### ISSUE TITLE
render credentials sometimes wipes ca.pem on v0.9.9-rc.2

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1003]
Steps:
* `init` a new cluster render
* Copy `ca.pem` and `ca-key.pem` into the credentials folder for this new cluster
* Run `render credentials`, all creds generated as expected
* Run `render credentials` again, for example after changing some LB config
* `ca.pem` is now empty

**Comment by razius** [comment]
Ah damn, this explains it. I wanted to update the config but couldn't figure out why all the commands are failing, I assumed it's something with the config. 

Is there a way to recover access to the cluster?

```
# kube-aws render stack

Generating credentials...
-> Parsing existing TLS CA
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xad9f64]

goroutine 1 [running]:
github.com/kubernetes-incubator/kube-aws/tlsutil.DecodeCertificatePEM(0xc4201c2c00, 0x0, 0x200, 0x0, 0x200, 0x0)
	/go/src/github.com/kubernetes-incubator/kube-aws/tlsutil/pem.go:32 +0x44
github.com/kubernetes-incubator/kube-aws/core/controlplane/config.(*Cluster).NewAssetsOnDisk(0xc42007c380, 0xe69bf8, 0xb, 0x0, 0xe77588, 0x18, 0xe72716, 0x14, 0xc42007c380, 0x0, ...)
	/go/src/github.com/kubernetes-incubator/kube-aws/core/controlplane/config/encrypted_assets.go:168 +0xb58
github.com/kubernetes-incubator/kube-aws/core/root/render.credentialsRendererImpl.RenderCredentials(0xc42007c380, 0x0, 0xe77588, 0x18, 0xe72716, 0x14, 0xc68280, 0x0)
	/go/src/github.com/kubernetes-incubator/kube-aws/core/root/render/credentials.go:30 +0x9f
github.com/kubernetes-incubator/kube-aws/cmd.runCmdRenderCredentials(0x154ce40, 0x1570bf8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/kubernetes-incubator/kube-aws/cmd/render.go:98 +0x106
github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra.(*Command).execute(0x154ce40, 0x1570bf8, 0x0, 0x0, 0x154ce40, 0x1570bf8)
	/go/src/github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x154d4a0, 0xc420183f50, 0x0, 0x0)
	/go/src/github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra.(*Command).Execute(0x154d4a0, 0xc4200001a0, 0xc4200001a0)
	/go/src/github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/go/src/github.com/kubernetes-incubator/kube-aws/main.go:10 +0x2d

# kube-aws validate --s3-uri s3://XXXXX                                                     

Error: Failed to initialize cluster driver: failed to render controller cloud config: cloud-config validation errors:
line 595: error: content cannot be decoded as "gzip+base64"
line 595: error: content cannot be decoded as "gzip+base64"
line 595: error: content cannot be decoded as "gzip+base64"
line 595: warning: incorrect type for "content" (want string)
line 595: warning: incorrect type for "content" (want string)
line 595: warning: incorrect type for "content" (want string)
```

**Comment by mumoshu** [comment]
@razius Sorry for the trouble.

ca.pem could be salvaged from the already running cluster or the s3 bucket specified in s3-uri.

Have you enabled TLS bootstrapping in cluster.yaml?
If that's the case, ca-key.pem could also be found there.

**Comment by c-knowles** [comment]
I have not looked at the original change for this yet, but I suspect one of these:

1. We don't need the symlink between `etcd-trusted-ca.pem` and `worker-ca.pem` to `ca.pem` if they do not absolutely need to be identical
1. If we must have the symlinks, we will likely need to remove any deletions from the code or check for contents

**Comment by c-knowles** [comment]
I've found worker-ca-key.pem is also empty, I assume it's not supposed to be.

**Comment by mumoshu** [comment]
Seems like I've reproduced it for ca.pem with v0.9.9-rc.1 with running `kube-aws inti` and then `kube-aws render credentials`x2. `worker-ca-key.pem` is still there with the content though.

**Comment by mumoshu** [comment]
After doing some poor-man's debug sessions with adhoc logs, it seems like we're writing to zero bytes through symlinks to ca.pem.

```
$ ../darwin-amd64/kube-aws render
WARNING: 'kube-aws render' is deprecated. See 'kube-aws render --help' for usage
Generating credentials...
-> Generating new TLS CA
-> Generating new assets
--> Summarizing the configuration
    Kubelet TLS bootstrapping enabled=true, TLS certificates managed by kube-aws=true, CA key required on controller nodes=true
--> Writing to the storage
Writing 1070 bytes to credentials/ca.pem
Writing 0 bytes to credentials/worker-ca.pem
Writing 0 bytes to credentials/worker-ca-key.pem
Writing 1277 bytes to credentials/apiserver.pem
Writing 1679 bytes to credentials/apiserver-key.pem
Writing 1172 bytes to credentials/worker.pem
Writing 1675 bytes to credentials/worker-key.pem
Writing 1119 bytes to credentials/admin.pem
Writing 1679 bytes to credentials/admin-key.pem
Writing 1155 bytes to credentials/etcd.pem
Writing 1675 bytes to credentials/etcd-key.pem
Writing 1094 bytes to credentials/etcd-client.pem
Writing 1675 bytes to credentials/etcd-client-key.pem
Writing 0 bytes to credentials/etcd-trusted-ca.pem
Writing 344 bytes to credentials/kubelet-tls-bootstrap-token
Writing 0 bytes to credentials/tokens.csv
Writing 1679 bytes to credentials/ca-key.pem
INFO: Removing a symlink worker-ca.pem to make it a symlink from ca.pemCreating a symlink from ca.pem to worker-ca.pem as there's no file
INFO: Removing a symlink etcd-trusted-ca.pem to make it a symlink from ca.pemCreating a symlink from ca.pem to etcd-trusted-ca.pem as there's no file
INFO: Removing a symlink worker-ca-key.pem to make it a symlink from ca-key.pemCreating a symlink from ca-key.pem to worker-ca-key.pem as there's no file
--> Verifying the result
Success! Stack rendered to ./stack-templates.

Next steps:
1. (Optional) Validate your changes to cluster.yaml with "kube-aws validate"
2. (Optional) Further customize the cluster by modifying templates in ./stack-templates or cloud-configs in ./userdata.
3. Start the cluster with "kube-aws up".
$ ../darwin-amd64/kube-aws render
WARNING: 'kube-aws render' is deprecated. See 'kube-aws render --help' for usage
Generating credentials...
-> Parsing existing TLS CA
-> Generating new assets
--> Summarizing the configuration
    Kubelet TLS bootstrapping enabled=true, TLS certificates managed by kube-aws=true, CA key required on controller nodes=true
--> Writing to the storage
Writing 1070 bytes to credentials/ca.pem
Writing 0 bytes to credentials/worker-ca.pem
Writing 0 bytes to credentials/worker-ca-key.pem
Writing 1277 bytes to credentials/apiserver.pem
Writing 1679 bytes to credentials/apiserver-key.pem
Writing 1172 bytes to credentials/worker.pem
Writing 1675 bytes to credentials/worker-key.pem
Writing 1119 bytes to credentials/admin.pem
Writing 1679 bytes to credentials/admin-key.pem
Writing 1155 bytes to credentials/etcd.pem
Writing 1679 bytes to credentials/etcd-key.pem
Writing 1094 bytes to credentials/etcd-client.pem
Writing 1675 bytes to credentials/etcd-client-key.pem
Writing 0 bytes to credentials/etcd-trusted-ca.pem
Writing 344 bytes to credentials/kubelet-tls-bootstrap-token
Writing 1679 bytes to credentials/ca-key.pem
INFO: Removing a symlink worker-ca.pem to make it a symlink from ca.pemCreating a symlink from ca.pem to worker-ca.pem as there's no file
INFO: Removing a symlink etcd-trusted-ca.pem to make it a symlink from ca.pemCreating a symlink from ca.pem to etcd-trusted-ca.pem as there's no file
INFO: Removing a symlink worker-ca-key.pem to make it a symlink from ca-key.pemCreating a symlink from ca-key.pem to worker-ca-key.pem as there's no file
--> Verifying the result
Success! Stack rendered to ./stack-templates.

Next steps:
1. (Optional) Validate your changes to cluster.yaml with "kube-aws validate"
2. (Optional) Further customize the cluster by modifying templates in ./stack-templates or cloud-configs in ./userdata.
3. Start the cluster with "kube-aws up".
```

**Comment by c-knowles** [comment]
It seems `worker-ca-key.pem` is only used when the TLS bootstrap experimental feature is enabled, I managed to update a cluster with this being zero bytes as I have not enabled that feature yet.

**Comment by mumoshu** [comment]
@c-knowles Thx. Would you mind taking a look into #1014?

**Comment by c-knowles** [comment]
@mumoshu Now I get this for a new cluster initialisation. All I've done it run `init`, copy in my ca.pem and ca-key.pem and then run render credentials:
```
➜ kube-aws render credentials

Generating credentials...
-> Parsing existing TLS CA
-> Generating new assets
--> Summarizing the configuration
    Kubelet TLS bootstrapping enabled=false, TLS certificates managed by kube-aws=true, CA key required on controller nodes=false
--> Writing to the storage
INFO: Writing 1151 bytes to credentials/ca.pem
INFO: Creating a symlink from worker-ca.pem to ca.pem
Error: Error creating assets: Not sure what to do for credentials/worker-ca-key.pem
```
