### ISSUE TITLE
api pods restart every 2.5 hours since using latest version

### ISSUE THREAD

**Issue by VinceMD** [kubernetes-incubator/kube-aws#1485]
I was using v0.9.10 of kube-aws with kubernetes v1.9.3.
I recently setup a new cluster using version v0.11 and v0.12.0. In each case I stick to the kubernetes version that is defined by kube-aws. 
Since using kube-aws v0.11, many pods in the kube-system namespaces are restarting very frequently for no obvious reason to me. Here is a new cluster created 20 hours ago with 9 restarts. It keeps happening every 2 or 3 hours:

```
NAME                                                                      READY   STATUS    RESTARTS   AGE
cluster-autoscaler-596967d4d9-djgt6                                       1/1     Running   8          19h
kube-apiserver-ip-10-11-37-74.ap-southeast-2.compute.internal             1/1     Running   9          19h
kube-apiserver-ip-10-11-38-139.ap-southeast-2.compute.internal            1/1     Running   9          19h
kube-controller-manager-ip-10-11-37-74.ap-southeast-2.compute.internal    1/1     Running   2          19h
kube-controller-manager-ip-10-11-38-139.ap-southeast-2.compute.internal   1/1     Running   3          19h
kube-scheduler-ip-10-11-37-74.ap-southeast-2.compute.internal             1/1     Running   1          19h
kube-scheduler-ip-10-11-38-139.ap-southeast-2.compute.internal            1/1     Running   2          19h
```

I'm printing above only the pods that have been restarted. Everything else has a zero restart.
My suspicion is that the api pods are restarting or down and the other ones then fail. Rather than each of them having an issue.

I'm not able to capture what triggers the restart. If I do a describe  on the api pod, there is no event. In the logs, it's very very verbose so I'm not sure what to look for. Maybe there is a keyword that I should look for that indicates a restart?

This is concerning to me and I'm very reluctant to put this cluster in production. If I terminate the controller and the pod, it happens again anyway after a few hours. It looks like every 2 to 3 hours, they restart.

**Comment by mumoshu** [comment]
@VinceMD Hey! Thanks for the report.

I have no clue on this yet but could you try capturing logs by `kubectl logs --previous`?

**Comment by VinceMD** [comment]
A lot aggregator error which are known issue I think: https://github.com/kubernetes/apiserver/issues/44


```
kubectl -n kube-system  logs --previous kube-apiserver-XXXX
W1108 05:03:18.978237       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
I1108 05:03:19.238334       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1108 05:03:19.242658       1 controller.go:111] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: OpenAPI spec does not exists
I1108 05:03:19.242680       1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
W1108 05:03:20.284738       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:20.289553       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:20.448924       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:20.455210       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:20.677060       1 x509.go:172] x509: subject with cn=system:kube-scheduler is not in the allowed list: [aggregator]
W1108 05:03:21.464481       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:21.470852       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:21.478182       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:21.497130       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:22.296395       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:22.301377       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:23.010342       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
I1108 05:03:23.838107       1 logs.go:49] http: TLS handshake error from 10.11.37.74:50292: EOF
W1108 05:03:24.013491       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:24.014256       1 x509.go:172] x509: subject with cn=system:kube-scheduler is not in the allowed list: [aggregator]
W1108 05:03:24.307773       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:24.312640       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:24.878550       1 x509.go:172] x509: subject with cn=system:kube-scheduler is not in the allowed list: [aggregator]
W1108 05:03:26.320034       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:26.325075       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:27.803979       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:27.809875       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:27.967706       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:27.978247       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:28.025656       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:28.025861       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:28.026657       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:28.168481       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:28.213855       1 x509.go:172] x509: subject with cn=system:kube-scheduler is not in the allowed list: [aggregator]
W1108 05:03:28.331480       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:28.336154       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:28.646560       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:30.344284       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:30.349326       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:32.301082       1 x509.go:172] x509: subject with cn=system:kube-scheduler is not in the allowed list: [aggregator]
W1108 05:03:32.356520       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
W1108 05:03:32.361306       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
I1108 05:03:33.838165       1 logs.go:49] http: TLS handshake error from 10.11.37.74:50330: EOF
W1108 05:03:33.911933       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-38-172.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
I1108 05:03:33.983824       1 autoregister_controller.go:160] Shutting down autoregister controller
I1108 05:03:33.983859       1 apiservice_controller.go:102] Shutting down APIServiceRegistrationController
I1108 05:03:33.983874       1 crdregistration_controller.go:143] Shutting down crd-autoregister controller
I1108 05:03:33.983890       1 available_controller.go:290] Shutting down AvailableConditionController
I1108 05:03:33.983906       1 crd_finalizer.go:254] Shutting down CRDFinalizer
I1108 05:03:33.983922       1 establishing_controller.go:84] Shutting down EstablishingController
I1108 05:03:33.983935       1 naming_controller.go:295] Shutting down NamingConditionController
I1108 05:03:33.983950       1 customresource_discovery_controller.go:210] Shutting down DiscoveryController
I1108 05:03:33.984205       1 controller.go:90] Shutting down OpenAPI AggregationController
I1108 05:03:33.991161       1 controller.go:158] Shutting down kubernetes service endpoint reconciler
I1108 05:03:33.991361       1 serve.go:136] Stopped listening on 127.0.0.1:8080
I1108 05:03:33.993262       1 serve.go:136] Stopped listening on [::]:443
E1108 05:03:34.002186       1 controller.go:160] no master IPs were listed in storage, refusing to erase all endpoints for the kubernetes service
```


```
kubectl -n kube-system  logs --previous kube-apiserver-YYYY
W1108 05:03:31.478758       1 x509.go:172] x509: subject with cn=system:node:ip-10-11-36-204.ap-southeast-2.compute.internal is not in the allowed list: [aggregator]
W1108 05:03:32.475317       1 x509.go:172] x509: subject with cn=system:kube-scheduler is not in the allowed list: [aggregator]
W1108 05:03:32.479249       1 x509.go:172] x509: subject with cn=system:kube-scheduler is not in the allowed list: [aggregator]
W1108 05:03:32.814680       1 x509.go:172] x509: subject with cn=system:kube-controller-manager is not in the allowed list: [aggregator]
I1108 05:03:33.540181       1 crdregistration_controller.go:143] Shutting down crd-autoregister controller
I1108 05:03:33.540292       1 establishing_controller.go:84] Shutting down EstablishingController
I1108 05:03:33.540314       1 naming_controller.go:295] Shutting down NamingConditionController
I1108 05:03:33.540329       1 customresource_discovery_controller.go:210] Shutting down DiscoveryController
I1108 05:03:33.540602       1 apiservice_controller.go:102] Shutting down APIServiceRegistrationController
I1108 05:03:33.540613       1 autoregister_controller.go:160] Shutting down autoregister controller
I1108 05:03:33.540622       1 available_controller.go:290] Shutting down AvailableConditionController
I1108 05:03:33.540631       1 crd_finalizer.go:254] Shutting down CRDFinalizer
I1108 05:03:33.541121       1 controller.go:158] Shutting down kubernetes service endpoint reconciler
I1108 05:03:33.541259       1 serve.go:136] Stopped listening on 127.0.0.1:8080
I1108 05:03:33.542126       1 serve.go:136] Stopped listening on [::]:443
I1108 05:03:33.540864       1 controller.go:90] Shutting down OpenAPI AggregationController
W1108 05:03:33.550667       1 lease.go:223] Resetting endpoints for master service "kubernetes" to [10.11.37.74]
```

**Comment by VinceMD** [comment]
```
kubectl -n kube-system  logs --previous  cluster-autoscaler-596967d4d9-djgt6
E1108 04:07:34.753840       1 event.go:260] Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'cluster-autoscaler-596967d4d9-djgt6 stopped leading'
I1108 04:07:34.754057       1 leaderelection.go:203] failed to renew lease kube-system/cluster-autoscaler: timed out waiting for the condition
F1108 04:07:34.754075       1 main.go:348] lost master
goroutine 1 [running]:
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.stacks(0xc4206f4400, 0xc421580b60, 0x37, 0xd9)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.(*loggingT).output(0x5618fa0, 0xc400000003, 0xc420d3d340, 0x52e7316, 0x7, 0x15c,0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:717 +0x348
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.(*loggingT).printf(0x5618fa0, 0x3, 0x36d1f2b, 0xb, 0x0, 0x0, 0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.Fatalf(0x36d1f2b, 0xb, 0x0, 0x0, 0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main.func3()
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:348 +0x51
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc420ce8000)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:141 +0x4a
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc420ce8000)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:148 +0xb4
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x553b800, 0xc420cd0d80, 0x37e11d600, 0x2540be400, 0x77359400, 0xc420cc6a10, 0x37d4808, 0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:157 +0x5a
main.main()
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:351 +0x727
```


```
kubectl -n kube-system  logs --previous  kube-controller-manager-ip-10-11-38-139.ap-southeast-2.compute.internal
ger" is forbidden: User "system:kube-controller-manager" cannot get endpoints in the namespace "kube-system"
E1108 04:47:15.239943       1 leaderelection.go:234] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get endpoints in the namespace "kube-system"
E1108 04:47:15.240088       1 event.go:259] Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'ip-10-11-38-139.aws.nbndc.local_d3f17d39-e30b-11e8-81a3-0a2a0f99731e stopped leading'
I1108 04:47:15.240200       1 leaderelection.go:213] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition
F1108 04:47:15.240367       1 controllermanager.go:215] leaderelection lost
```


```
kubectl -n kube-system  logs --previous  kube-scheduler-ip-10-11-38-139.ap-southeast-2.compute.internal
E1108 05:03:54.486525       1 leaderelection.go:234] error retrieving resource lock kube-system/kube-scheduler: Get https://127.0.0.1/api/v1/namespaces/kube-system/endpoints/kube-scheduler: net/http: TLS handshake timeout
E1108 05:03:54.486770       1 event.go:259] Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'ip-10-11-38-139.aws.nbndc.local_436e4807-e307-11e8-a2e7-0a2a0f99731e stopped leading'
I1108 05:03:54.486981       1 leaderelection.go:213] failed to renew lease kube-system/kube-scheduler: timed out waiting for the condition
E1108 05:03:54.487100       1 server.go:194] lost master
lost lease
```

**Comment by VinceMD** [comment]
Checking the journalctl of the node at the time of when the api server decided to shutdown today:

```Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local sh[1337]: E1109 00:18:48.130170    1337 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Get http://localhost:8080/api/v1/nodes?>
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local sh[1337]: E1109 00:18:48.135943    1337 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get http://localhost:8080/api/v1>
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local sh[1337]: E1109 00:18:48.140411    1337 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Get http://localhost:8080/api/v1/ser>
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local env[685]: time="2018-11-09T11:18:48+11:00" level=info msg="shim reaped" id=09f7491e35fe554d62f69e08e855d2fbdf490768dd165cf78c165d119fe4d279
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local env[788]: time="2018-11-09T11:18:48.483902456+11:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local sh[1337]: I1109 00:18:48.567839    1337 kuberuntime_manager.go:757] checking backoff for container "kube-apiserver" in pod "kube-apiserver-ip-10-11-36-42.ap-southeast-2>
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local systemd[1]: Failed to set up mount unit: Invalid argument
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local env[685]: time="2018-11-09T11:18:48+11:00" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/b0a79f7e21ff69514fa77ff50f9b875edffe65c006482afc>
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local env[685]: time="2018-11-09T11:18:48+11:00" level=debug msg="registering ttrpc server"
Nov 09 11:18:48 ip-10-11-36-42.aws.nbndc.local env[685]: time="2018-11-09T11:18:48+11:00" level=debug msg="serving api on unix socket" socket="[inherited from parent]"```

**Comment by VinceMD** [comment]
This issue has slowed down with only one occurrence in last 2 days whereas it used to be every 2 hours. Maybe something wrong in this AWS account, but I would have liked to understand what triggered what seems to be a graceful shutdown of apiserver

**Comment by paalkr** [comment]
Probably not helpful, but my 45 node kube-aws v0.11.0 cluster does not have this issue. We could try to identify where the differences are.
