### ISSUE TITLE
Panic on `kube-aws update` if fetching existing stack was problematic

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#246]
I ran `kube-aws update`  while network/aws service was unstable, it made it fail:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x485d83]

goroutine 1 [running]:
panic(0xa162a0, 0xc420010190)
	/home/rossmohax/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/kube-aws/cluster.(*Cluster).lockEtcdResources(0xc4203ce000, 0xc4203e4100, 0xc4201ea000, 0x10364, 0x0, 0xc4203e4108, 0x0, 0xc4205c2000)
	/home/rossmohax/gocode/kube-aws/src/github.com/coreos/kube-aws/cluster/cluster.go:228 +0x2e3
github.com/coreos/kube-aws/cluster.(*Cluster).Update(0xc4203ce000, 0xc4201ea000, 0x10364, 0x7ffcfd3e0f3e, 0x33, 0x10364, 0x0, 0x0, 0xc4201583e0)
	/home/rossmohax/gocode/kube-aws/src/github.com/coreos/kube-aws/cluster/cluster.go:270 +0x143
github.com/coreos/kube-aws/cmd.runCmdUpdate(0xeeac40, 0xc4200e31c0, 0x0, 0x2, 0x0, 0x0)
	/home/rossmohax/gocode/kube-aws/src/github.com/coreos/kube-aws/cmd/update.go:50 +0x2a7
github.com/coreos/kube-aws/vendor/github.com/spf13/cobra.(*Command).execute(0xeeac40, 0xc4200e30c0, 0x2, 0x2, 0xeeac40, 0xc4200e30c0)
	/home/rossmohax/gocode/kube-aws/src/github.com/coreos/kube-aws/vendor/github.com/spf13/cobra/command.go:632 +0x23e
github.com/coreos/kube-aws/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xeea5e0, 0x0, 0x0, 0x0)
	/home/rossmohax/gocode/kube-aws/src/github.com/coreos/kube-aws/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/coreos/kube-aws/vendor/github.com/spf13/cobra.(*Command).Execute(0xeea5e0, 0xc420157f50, 0xc4200001a0)
	/home/rossmohax/gocode/kube-aws/src/github.com/coreos/kube-aws/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/home/rossmohax/gocode/kube-aws/src/github.com/coreos/kube-aws/main.go:9 +0x2d
```

Looking at the code:

```
        //Fetch and unmarshal existing stack resource defintions
        res, err := cfSvc.GetTemplate(&cloudformation.GetTemplateInput{
                StackName: aws.String(c.StackName()),
        })
        if err != nil {
                return "", fmt.Errorf("error getting stack template: %v", err)
        }
        var existingStack cfStackResources
        if err := json.Unmarshal([]byte(*res.TemplateBody), &existingStack); err != nil {
                return "", fmt.Errorf("error unmarshaling existing stack json: %v", err)
        }
```

apparently  there can possibly be a case where `err == nil` and `res.TemplateBody == nil`

**Comment by mumoshu** [comment]
Thanks for the report.
This was unintentionally fixed in v0.9.4 😄
