### ISSUE TITLE
Cluster with apiEndpoints set fails to come up

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#527]
Bringing up a new cluster up on latest master ae4956992dcea09a3b6f0973a2822f4875d1859c does not seem to work for config with `apiEndpoints` from https://github.com/kubernetes-incubator/kube-aws/pull/468, the workers fail to join the cluster.

With this config all works fine as before and the cluster comes up:

```
externalDNSName: k8s-dev-v1.REDACTED
createRecordSet: true
recordSetTTL: 60
#hostedZone: ""
hostedZoneId: REDACTED
```

But switching to this config where everything else is identical the workers fail to become "healthy":

```
#externalDNSName: k8s-dev-v1.REDACTED
#createRecordSet: true
#recordSetTTL: 60
#hostedZone: ""
#hostedZoneId: REDACTED

apiEndpoints:
  - name: versioned
    createRecordSet: true
    dnsName: k8s-dev-v1.REDACTED
    hostedZone:
      id: REDACTED
    recordSetTTL: 60
  - name: unversioned
    dnsName: k8s-dev.REDACTED

worker:
  apiEndpointName: versioned
```

The control plane stack ended up with resource `APIEndpointVersionedELB` and the update there update was complete pending cleanup. It was just the worker stack that failed to update.

In case anyone ends up here also, currently it seems impossible to `kube-aws update` a cluster when moving to `apiEndpoints` without updating the endpoints to a disjointed set. This is because CloudFormation tries to add a Route 53 RecordSet with the same value but different resource Logical ID. Workaround is to ensure endpoint DNS names do not contain existing `externalDNSName`.

**Comment by c-knowles** [comment]
Checking the worker that had to be rolled back (before it disappeared) reveals at least these errors:

```
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x969c25]
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: goroutine 1 [running]:
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: panic(0x3a34940, 0xc420018030)
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes.(*Clientset).Events(0x0, 0x0, 0x0, 0x0, 0x0)
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]:         <autogenerated>:25 +0x5
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: k8s.io/kubernetes/cmd/kubelet/app.makeEventRecorder(0xc420cdb200, 0xc420736780, 0xc42104e8d0, 0x28)
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:348 +0x1ba
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: k8s.io/kubernetes/cmd/kubelet/app.run(0xc420cdb200, 0xc420736780, 0x498068, 0xc420e3d900)
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:505 +0x2c2
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: k8s.io/kubernetes/cmd/kubelet/app.Run(0xc420cdb200, 0x0, 0xc420e3d910, 0xc420e3d920)
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:285 +0x39
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: main.NewKubelet.func1(0xc4208050e0, 0xc420719320, 0x0, 0x11, 0x0, 0x0)
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/kubelet.go:38 +0x33
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: main.(*HyperKube).Run(0xc42005b440, 0xc42000c130, 0x11, 0x11, 0x0, 0x0)
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:179 +0x468
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: main.(*HyperKube).RunToExit(0xc42005b440, 0xc42000c120, 0x12, 0x12)
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:189 +0x61
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]: main.main()
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal kubelet-wrapper[2164]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/main.go:47 +0x853
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal systemd[1]: kubelet.service: Unit entered failed state.
Apr 11 02:34:28 ip-10-0-24-56.eu-west-1.compute.internal systemd[1]: kubelet.service: Failed with result 'exit-code'.
Apr 11 02:34:38 ip-10-0-24-56.eu-west-1.compute.internal systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Apr 11 02:34:38 ip-10-0-24-56.eu-west-1.compute.internal systemd[1]: Stopped kubelet.service.
```

```
Apr 11 02:34:42 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to open directory /run/user/500/systemd/transient/var-lib-rkt-pods-run-60ca7ae9\x2d4043\x2d4d6c\x2da194\x2d892ac60b8a7c-stage1-rootfs-opt-stage2-hyperkube-rootfs-var-lib-rkt-pods-run-bf768a84\x2dc2fc\x2d49d4\x2d99da\x2de8a273d0638d-stage1-rootfs-opt-stage2-hyperkube-rootfs-usr-lib-os\x2drelease.mount.wants: File name too long
Apr 11 02:34:42 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to open directory /run/user/500/systemd/transient/var-lib-rkt-pods-run-60ca7ae9\x2d4043\x2d4d6c\x2da194\x2d892ac60b8a7c-stage1-rootfs-opt-stage2-hyperkube-rootfs-var-lib-rkt-pods-run-bf768a84\x2dc2fc\x2d49d4\x2d99da\x2de8a273d0638d-stage1-rootfs-opt-stage2-hyperkube-rootfs-usr-lib-os\x2drelease.mount.requires: File name too long
Apr 11 02:34:42 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to open directory /etc/systemd/user/var-lib-rkt-pods-run-60ca7ae9\x2d4043\x2d4d6c\x2da194\x2d892ac60b8a7c-stage1-rootfs-opt-stage2-hyperkube-rootfs-var-lib-rkt-pods-run-bf768a84\x2dc2fc\x2d49d4\x2d99da\x2de8a273d0638d-stage1-rootfs-opt-stage2-hyperkube-rootfs-usr-lib-os\x2drelease.mount.wants: File name too long
Apr 11 02:34:42 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to open directory /etc/systemd/user/var-lib-rkt-pods-run-60ca7ae9\x2d4043\x2d4d6c\x2da194\x2d892ac60b8a7c-stage1-rootfs-opt-stage2-hyperkube-rootfs-var-lib-rkt-pods-run-bf768a84\x2dc2fc\x2d49d4\x2d99da\x2de8a273d0638d-stage1-rootfs-opt-stage2-hyperkube-rootfs-usr-lib-os\x2drelease.mount.requires: File name too long
```

```
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to set up mount unit: Invalid argument
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to set up mount unit: Invalid argument
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1]: Failed to set up mount unit: Invalid argument
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1]: Failed to set up mount unit: Invalid argument
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to set up mount unit: Invalid argument
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1]: Failed to set up mount unit: Invalid argument
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to set up mount unit: Invalid argument
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to set up mount unit: Invalid argument
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to set up mount unit: Invalid argument
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to set up mount unit: Invalid argument
Apr 11 02:35:11 ip-10-0-24-56.eu-west-1.compute.internal systemd[1144]: Failed to set up mount unit: Invalid argument
```

**Comment by redbaron** [comment]
panic in kubelet IMHO should be reported to kubernetes

**Comment by c-knowles** [comment]
@redbaron OK, I can report assuming I can give them enough details. All I have right now is the above though.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the report.
It definitely seems like my tests were not sufficient and a terrible bug that the various refs throughout kubeconfig and cloud-config-worker become empty when there're 2 or more API endpoints defined in cluster.yaml.
I've already finished the fix in my local branch and I'll update the master branch shortly after more careful testings.

**Comment by c-knowles** [comment]
@mumoshu OK, I had noticed the kubeconfig issue somewhere else but not related the two things. Is there anything we can to about switching from default to `apiEndpoints` not working with `kube-aws update`? Perhaps I just have to name one of the endpoints `default`?

**Comment by mumoshu** [comment]
@c-knowles I'm still a bit unsure about your case.

So, in other words, you'd like to name your former record set and the newer record set both created for `k8s-dev-v1.REDACTED` the same in a cloudformation stack? So that `kube-aws update` can be used to migrate your cluster initially created with `externalDNSName`, to a newer version with no `externalDNSName` but `apiEndpoints`?

**Comment by c-knowles** [comment]
@mumoshu exactly yes. Since the validation ensures I cannot use both the old and new settings together the typical path to using this will almost certainly be:

Previous config:
```
externalDNSName: original-domain
```

New config:
```
apiEndpoints:
  - name: original
    dnsName: original-domain
  - name: additional
    dnsName: additional-domain
```

But doing this causes `kube-aws update` to not work due to the reason above.

**Comment by mumoshu** [comment]
This issue was automatically closed via #529 but please feel free to reopen and add more GitHub issues if necessary.

**Comment by mumoshu** [comment]
@c-knowles I'm not very happy to say something like this but will you be ok with the current situation as:

* I believe the path [mentioned in your comment](https://github.com/kubernetes-incubator/kube-aws/issues/527#issuecomment-293460657) is already supported as long as `kube-aws up` and `kube-aws update` with the respective configuration is executed with the same version of kube-aws
* And there's already [a general guidance](https://github.com/kubernetes-incubator/kube-aws/issues/455) that we recommend users to recreate clusters when upgrading kube-aws

?

Please feel free to point out if I'm missing other aspects of the use-case.

**Comment by c-knowles** [comment]
@mumoshu I tried again today but the path I mentioned doesn't work even with the same version of kube-aws.

Steps to reproduce:
1. Create a cluster using `externalDNSName`
2. Migrate to `apiEndpoints`, at least one of the endpoints will be the same as the old `externalDNSName` (this is the typical migration path)
3. Run `kube-aws update`
4. CloudFormation tries to create a resource `APIEndpoint<API ENDPOINT NAME>ELBRecordSet` but the DNS name is already taken by `APIEndpointDefaultELBRecordSet` from the previous version of the same stack

This is the exact error:
```
12:25:40 UTC+0800	CREATE_FAILED	AWS::Route53::RecordSet	APIEndpoint<REDACTED>ELBRecordSet	Tried to create resource record set [name='<REDACTED>', type='CNAME'] but it already exists
```

I can workaround this, my question is just is there anything we could do to ease migration? e.g. make one of the endpoints the "default" (and name the resource `APIEndpointDefaultELBRecordSet`)

One workaround without creating a whole new cluster is manually change the existing Route 53 entry and just add a single character so the original name can be created again by the stack.

**Comment by c-knowles** [comment]
I've updated a dev cluster today with the changes on master and everything seems good this time around, workers all joining correctly. I'm wondering if I should report the panic to kubernetes, I believe the config we were passing was likely to `https://:443` which makes very little sense but probably should return a validation error.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the detailed feedback!
Making one of endpoints named `default` would work.
However, If we only intend to support the upgrade path from `externalDNSName` to `apiEndpoints` within the same kube-aws version, perhaps we'd better deprecate `externalDNSName` and pre-populate the first item of `apiEndpoints` in cluster.yaml, rather than the set of old `externalDNSName`, `createRecordSet`, etc?

**Comment by mumoshu** [comment]
Hmmm, I'm not sure why it worked for you this time. I guess we made no change around it since then.

Regarding the panic, I think it would be a low-priority thing as I believe there're relatively a small amount of users face the issue. However, the bug is a bug - submitting an issue for it would be very helpful!

**Comment by c-knowles** [comment]
@mumoshu I'm all for deprecation if it simplifies `kube-aws`. In particular I'm not a fan of many layers of configuration/defaulting because I think it's sometimes hard to determine what the value will end up being. So I would agree it's probably better to deprecated `externalDNSName` and just populate first items of `apiEndpoints`.

As for why it worked this time, sorry for the confusion as I just meant your fixes on master. I still performed my workaround for the Route 53 RecordSet otherwise the stack always fails to update, I didn't want to waste the time to create a whole new stack just to change one DNS entry 😆

**Comment by c-knowles** [comment]
I found the flag related to the panic above is deprecated flag so I filed a separate issue to sort that out in kube-aws. Not sure if switching to non-deprecated flags will still have the same problem but since it's a small case I'm not going to pursue it further right now.
